/**
 * This file is autogenerated by AssetChain_Starterkits.(inspired by scaffold-eth)
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  
};

export default deployedContracts;


