/**
 * This file is autogenerated by AssetChain_Starterkits.(inspired by scaffold-eth)

 * @author ASSETCHAIN DEVREL TEAM
 *  @author James Harrison(https://github.com/KodeSage/)
 *  @author  Okorie Ebube(https://github.com/theiceeman)

 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {

};

export default deployedContracts;
